tests/test_scripts/hadoop2_test.sh

Fixed path to yarn-daemon.sh so the services don't have to be killed manually.

tests: hadoop2: fix path typo in script

---

tests/cronjob/run_xtreemfs_tests.sh
tests/test_config.py
tests/test_scripts/14_xtfs_benchmark.sh

Because the file based benchmarks produce a large number of files, it is both necessary to:
- Make sure that there is not only enough space available, but also sufficiently many i-nodes and
- Increase the file size in the file based benchmarks to reduce the number of files produced.

Making sure there are enough i-nodes, reduced number of files in benchmark

---

tests/test_scripts/junit_tests.sh

netstat -a instead of -l in order to get TIME_WAIT connections as well (instead of LISTEN only). Only wait in case of a test failure to avoid prolonging test execution unnecessarily.

Waiting for ports to become free on JUnit test failure

---

cpp/src/libxtreemfs/options.cpp

Only options that had both a long and short version would be recognized correctly when parsing the alternative options specification (e.g. from /etc/fstab). Now either of them can be missing and the case is handled correctly. Fixes #372

More careful alternative options parsing, fixing #372

---

.travis.yml

Since the coverity_scan branch will contain its own .travis.yml file, there is no need to specify the coverity_scan addon in the master branch's .travis.yml file.

Separate .travis.yml file for master branch

---

.travis.yml
merge.sh

The coverity scan is only ever run on the coverity_scan branch. In order to save resources, this branch's .travis.yml file contains the coverity scan addon only. Otherwise the scan would be run for each entry of the build matrix (cf. TEST_SUITE in the master branch's .travis.yml file). The helper merge script merges from a target branch into coverity_scan, resolving conflicts by keeping the coverity_scan branch's version. This will only concern the .travis.yml file.

Separate .travis.yml file for coverity_scan branch

---

tests/test_config.py
tests/test_scripts/coverity_scan_test.sh

This PR adds the Coverity Scan to the set of tests that is run each night. The current master is merged into coverity_scan and pushed to GitHub. Travis CI will pick up on the coverity_branch and run the Coverity Scan.

Run Coverity Scan each night with the other tests

---

tests/cronjob/run_xtreemfs_tests.sh

The Coverity Scan test requires push access to the xtreemfs repository. The public key of the user on the server that the nightly tests run on has been added as a deploy key. SSH clones create a remote URL with SSH so pushes to origin won't ask for username/password. This allows for non-interactive nightly Coverity Scan tests.

Use SSH clone in test so subsequent pushes wont ask for username/password

---

contrib/hadoop/src/org/xtreemfs/common/clients/hadoop/XtreemFSFileSystem.java

- Allowing explicit specification of default volume in paths
- Skipping link to current and parent directory in default volume during initialization

Hadoop improvements

---

java/servers/src/org/xtreemfs/mrc/operations/CreateDirOperation.java
java/servers/src/org/xtreemfs/mrc/operations/OpenOperation.java
java/servers/test/org/xtreemfs/common/libxtreemfs/VolumeTest.java

It is common to most POSIX filesystems to inherit the group id if the setgid bit is set on a directory [0].
This commit introduces group inheritance to the MRC and fixes issue #385. 
Although i am not sure if this is part of the POSIX standard it could be useful to implement it in regard to compatibility. 
[0] https://www.gnu.org/software/coreutils/manual/html_node/Directory-Setuid-and-Setgid.html

Inherit groupId if setgid is set. 

---

tests/manual_config.py
tests/xtestenv

Currently 1 DIR, 1 MRC and 3 OSDs are started. This could be changed as well as the number of automatic created and mounted volumes.

 Add separate config for manual xtestenvs which does not require allow_other.

---

contrib/hadoop/src/org/xtreemfs/common/clients/hadoop/XtreemFSFileOutputStream.java

Some frameworks (such as Apache Flink) close the output stream multiple times. To avoid segmentation faults, this PR adds a check to make sure an already closed output stream cannot be closed again.

Prevent multiple closing of XtreemFSFileOutputStream

---

cpp/test/rpc/client_ssl_test.cpp

This PR fixes CID 119725 and tries to fix parts of CID 119729. As the latter requires some engineering, this is a first check to see if Coverity is happy with the changes, and if so, the remaining parts of CID 119729 will be fixed tomorrow.

Coverity fixes in client SSL test

---

.travis.yml
contrib/hadoop/build.xml
contrib/hadoop/nbproject/build-impl.xml
tests/test_scripts/hadoop_junit_tests.sh

This PR fixes the XtreemFS Hadoop adapter test compilation and execution dependencies when not run from NetBeans. If in NetBeans, these properties need to be specified within the project. If not in NetBeans, the environment variable HADOOP_PREFIX needs to be defined for the tests to be compiled and executed.
Furthermore Travis CI has been switched to use OpenJDK 7.

Fix external Hadoop dependencies

---

java/xtreemfs-servers/src/main/java/org/xtreemfs/utils/utils.java
java/xtreemfs-servers/src/main/java/org/xtreemfs/utils/xtfs_benchmark/CLIOptions.java
java/xtreemfs-servers/src/main/java/org/xtreemfs/utils/xtfs_chstatus.java
java/xtreemfs-servers/src/main/java/org/xtreemfs/utils/xtfs_cleanup_osd.java
java/xtreemfs-servers/src/main/java/org/xtreemfs/utils/xtfs_mrcdbtool.java
java/xtreemfs-servers/src/main/java/org/xtreemfs/utils/xtfs_remove_osd.java
java/xtreemfs-servers/src/main/java/org/xtreemfs/utils/xtfs_scrub/xtfs_scrub.java

This PR makes the `admin_password` command line option "promptable", i.e. if a dash (-) is passed as a password, then the password will be prompted. Furthermore, to add support for non-interactive shells, a fallback to `System.in` has been added to allow piping of prompted passwords using `<`.

Command Line Parsing Improvements

---

cpp/src/xtfsutil/xtfsutil.cpp
interface/xtreemfs/GlobalTypes.proto
java/xtreemfs-servers/src/main/java/org/xtreemfs/mrc/MRCPolicyContainer.java
java/xtreemfs-servers/src/main/java/org/xtreemfs/mrc/operations/GetSuitableOSDsOperation.java
java/xtreemfs-servers/src/main/java/org/xtreemfs/mrc/operations/GetXLocSetOperation.java
java/xtreemfs-servers/src/main/java/org/xtreemfs/mrc/operations/OpenOperation.java
java/xtreemfs-servers/src/main/java/org/xtreemfs/mrc/osdselection/FileNamePrefixPolicy.java
java/xtreemfs-servers/src/main/java/org/xtreemfs/mrc/osdselection/FilterDefaultPolicy.java
java/xtreemfs-servers/src/main/java/org/xtreemfs/mrc/osdselection/FilterFQDNPolicy.java
java/xtreemfs-servers/src/main/java/org/xtreemfs/mrc/osdselection/FilterUUIDPolicy.java
java/xtreemfs-servers/src/main/java/org/xtreemfs/mrc/osdselection/GroupDCMapPolicy.java
java/xtreemfs-servers/src/main/java/org/xtreemfs/mrc/osdselection/GroupFQDNPolicy.java
java/xtreemfs-servers/src/main/java/org/xtreemfs/mrc/osdselection/OSDSelectionPolicy.java
java/xtreemfs-servers/src/main/java/org/xtreemfs/mrc/osdselection/OSDStatusManager.java
java/xtreemfs-servers/src/main/java/org/xtreemfs/mrc/osdselection/PolicyHelper.java
java/xtreemfs-servers/src/main/java/org/xtreemfs/mrc/osdselection/PreferredUUIDPolicy.java
java/xtreemfs-servers/src/main/java/org/xtreemfs/mrc/osdselection/SortDCMapPolicy.java
java/xtreemfs-servers/src/main/java/org/xtreemfs/mrc/osdselection/SortFQDNPolicy.java
java/xtreemfs-servers/src/main/java/org/xtreemfs/mrc/osdselection/SortHostRoundRobinPolicy.java
java/xtreemfs-servers/src/main/java/org/xtreemfs/mrc/osdselection/SortRandomPolicy.java
java/xtreemfs-servers/src/main/java/org/xtreemfs/mrc/osdselection/SortReversePolicy.java
java/xtreemfs-servers/src/main/java/org/xtreemfs/mrc/osdselection/SortUUIDPolicy.java
java/xtreemfs-servers/src/main/java/org/xtreemfs/mrc/osdselection/SortVivaldiPolicy.java
java/xtreemfs-servers/src/main/java/org/xtreemfs/mrc/osdselection/VolumeOSDFilter.java
java/xtreemfs-servers/src/main/java/org/xtreemfs/mrc/utils/MRCHelper.java
java/xtreemfs-servers/src/test/java/org/xtreemfs/test/mrc/OSDPolicyTest.java

Extended OSDSelectionPolicy interface such that getOSDs now receives the file path as parameter. 
Added an OSDSelectionPolicy that selects OSDs based on file path prefixes.
commit 57e354e is reverted by commit 097a298 (which does nothing but reverting 57e354e), hence only commits 78aa1ba and f2cc801 carry actual change.

Extended OSDSelectionPolicy interface

---

cpp/src/cbfs/cbfs_adapter.cpp

See comment in the code. In effect the client would always request RW access, even if read-only would have been sufficient. This would, for example, prevent an -r-xr-xr-x file (on the server) from being copied onto a machine using the Windows client.

STANDARD_ACCESS_WRITE does not necessarily indicate desired write access

---

java/xtreemfs-servers/src/main/java/org/xtreemfs/mrc/osdselection/FileNamePrefixPolicy.java
java/xtreemfs-servers/src/main/java/org/xtreemfs/mrc/osdselection/PreferredUUIDPolicy.java
java/xtreemfs-servers/src/test/java/org/xtreemfs/test/mrc/OSDPolicyTest.java

The default behaviour of the OSDSelectionPolicies PreferredUUIDPolicy and FileNamePrefixPolicy is changed such that:
- when an OSD corresponding to the configuration of the policy is found, it is the first element in the list of returned OSDs; all other OSDs are appended to this list in random order.
- when no OSD corresponding to the configuration of the policy is found, all available OSDs are returned in random order.
This is more similar to the normal behaviour (when no OSDSelectionPolicy is explicitly chosen, the SortRandomPolicy is used). 
It prevents that a whole XtreemFS setup is dependant on a single OSD.

changed default behaviour of OSDSelectionPolicies

---

cpp/src/rpc/client.cpp

cpp: use accessor function for SSL context

---

interface/xtreemfs/MRC.proto
java/xtreemfs-servers/src/main/java/org/xtreemfs/mrc/operations/AddReplicaOperation.java
java/xtreemfs-servers/src/main/java/org/xtreemfs/mrc/operations/MarkReplicaCompleteOperation.java
java/xtreemfs-servers/src/main/java/org/xtreemfs/mrc/operations/RemoveReplicaOperation.java
java/xtreemfs-servers/src/main/java/org/xtreemfs/mrc/operations/SetReplicaUpdatePolicyOperation.java
java/xtreemfs-servers/src/main/java/org/xtreemfs/mrc/stages/ProcessingStage.java
java/xtreemfs-servers/src/main/java/org/xtreemfs/mrc/utils/MRCHelper.java
java/xtreemfs-servers/src/main/java/org/xtreemfs/osd/drain/OSDDrain.java
java/xtreemfs-servers/src/main/java/org/xtreemfs/osd/replication/ObjectDissemination.java
java/xtreemfs-servers/src/test/java/org/xtreemfs/test/mrc/MRCTest.java

partially fixing issue 223: it is no longer possible to delete a replica of a file if it is the only complete one (i.e., has all the objects of that file).
deleting such a replica eventually becomes possible, when another OSD has a complete replica of that file.
if using read-only replication policy with a striping policy that uses more than one OSD per file, it might (with relatively low probability) still be possible to lose data, as described in issue 223.

towards a fix of issue 223
